FEDERATION_SERVER="https://federate.clickpesa.com/federation"
AUTH_SERVER = "https://compliance.clickpesa.com"


[DOCUMENTATION]
ORG_NAME="Payclick Limited"
ORG_DBA="ClickPesa"
ORG_URL="https://clickpesa.com"
ORG_DESCRIPTION="ClickPesa offers a toolbox with payment solutions making it easier to receive and make payments for your business."
ORG_PHYSICAL_ADDRESS="Plot 1133, Haile Selassie Rd, Msasani Peninsula Dar es Salaam – Tanzania"
ORG_PHONE_NUMBER="+255 (0) 763 661 111"
ORG_TWITTER="clickpesa"
ORG_OFFICIAL_EMAIL="info@clickpesa.com"


ACCOUNTS=[
"GA6WRVV7W2XJTIGBOHR37HZM2X3AAINJ76UNRTWBBXUBWNMJCKWTMID3",
"GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO"
]


[[CURRENCIES]]
code="TZS"
issuer="GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO"
display_decimals=2 
name="Tanzania Shilling"
desc="TZS will always equal 1 TZS and is backed by audited accounts"
name="TZS"
host="https://clickpesa.com"
countries="TZ"
anchor_asset_type="fiat"
anchor_asset="TZS"

[[CURRENCIES]]
code="USD"
issuer="GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO"
display_decimals=2 
name="US Dollar"
desc="USD will always equal 1 USD and is backed by audited accounts"
name="USD"
host="https://clickpesa.com"
countries="TZ"
anchor_asset_type="fiat"
anchor_asset="TZS"

[[CURRENCIES]]
code="EURO"
issuer="GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO"
display_decimals=2 
name="EURO"
desc="EURO will always equal 1 EURO and is backed by audited accounts"
name="EURO"
host="https://clickpesa.com"
countries="TZ"
anchor_asset_type="fiat"
anchor_asset="TZS"

[[CURRENCIES]]
code="AUD"
issuer="GA2MSSZKJOU6RNL3EJKH3S5TB5CDYTFQFWRYFGUJVIN5I6AOIRTLUHTO"
display_decimals=2 
name="AUD"
desc="AUD will always equal 1 AUD and is backed by audited accounts"
name="AUD"
host="https://clickpesa.com"
countries="TZ"
anchor_asset_type="fiat"
anchor_asset="TZS"



[[PRINCIPALS]]
name="Omar"
email="omar@clickpesa.com"


###################################
#
# Minimum Settlement Amount : 50 USD, 50 EURO, 50 AUD, 120,000 TZS
# Maximum Settlement Amount : 10,000 USD, 10,000 EURO, 10,000 AUD, 10,000,000 TZS